# -*- coding: utf-8 -*-
"""RITA Africa, Lesson 4 Assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LgcEFpHg45KS5-FIil_6Cv3QuAyJahz
"""

"""
Individual Exercise: Age Group Categorization

Create a Python script that categorizes a person into different age groups based on their age.
Your script should:
1. Define a variable age to store the person's age(as an integer)
2. Using if-elif-else statements, determine the age group based on the following criteria:
If the age is less than 0, print an error message stating that age cannot be negative.
If the age is between 0 and 12 (inclusive), categorize the person as "Child".
If the age is between 13 and 19 (inclusive), categorize the person as "Teenager"
If the age is between 20 and 64(inclusive), categorize the person as "Adult"
If the age is 65 or older, categorize the person as "Senior"

3. Print the age group category based on the age provided.
"""

# Defining a variable to store the person's age
age = int(input("Enter the person's age: "))

# Determining the age group using if-elif-else statements
if age < 0:
    print("Error: Age cannot be negative.")
elif age <= 12:
    category = "Child"
elif 13 <= age <= 19:
    category = "Teenager"
elif 20 <= age <= 64:
    category = "Adult"
else:  # age 65 or older
    category = "Senior"

# Printing the age group category
if age >= 0:
    print(f"The person is categorized as: {category}")

"""
Group Exercise: Price Categorization:
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
Create a python script that categorizes a product based on its price. Your script should:

Define a variable to store the product's price (a float or integer)
Using if-elif-else statements, determine the price category based on the following criteria:

If the price is less than or equal to 10, categorize the product as "Cheap" If the price is between 11 and 50(inclusive), categorize the product as "Affordable" If the price is between 51 and 100(Inclusive), categorize the product as "Moderate" If the price is greater than 100, categorize the product as "Expensive"

Print the price category based on the price provided
"""

# Defining a variable to store the product's price
price = float(input("Enter the product's price: "))

# Determining the price category using if-elif-else statements
if price <= 10:
    category = "Cheap"
elif 11 <= price <= 50:
    category = "Affordable"
elif 51 <= price <= 100:
    category = "Moderate"
else:
    category = "Expensive"

# Printing the price category
print(f"The product is categorized as: {category}")

